---
# http://docs.ansible.com/ansible/latest/apt_key_module.html
- name: Add repository key
  apt_key:
    keyserver: "keyserver.ubuntu.com"
    id: "1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B"
    state: present

# http://docs.ansible.com/ansible/latest/apt_repository_module.html
- name: Add Server repository
  apt_repository:
    repo: 'deb [arch=amd64] https://pkg.osquery.io/deb deb main'
    state: present

- name: Update apt cache
  apt: update_cache=yes

