---

- name: Install Redhat | Add yum repository
  yum_repository:
    name: td-agent-bit
    baseurl: 'https://packages.fluentbit.io/centos/7/x86_64/td-agent-bit-1.7.9-1.x86_64.rpm'
    gpgcheck: true
    gpgkey: https://packages.fluentbit.io/fluentbit.key
    description: Fluent bit repo
    enabled: yes


- name: Add Server repository
  yum_repository:
    name: osquery
    description: 'name=osquery RPM repository - x86_64'
    baseurl: 'https://s3.amazonaws.com/osquery-packages/rpm/$basearch/'
    gpgkey: https://pkg.osquery.io/rpm/GPG
    gpgcheck: true
    enabled: true

